{{- if .Values.gateways }}
{{- range .Values.gateways }}
{{- if .enabled }}
{{- $gw := mustMergeOverwrite (deepCopy $.Values.gatewayDefaults) . }}
{{- $ctx := dict "gw" $gw "Chart" $.Chart "Release" $.Release }}
{{- if $gw.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gateways.serviceAccountName" $ctx }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gateways.labels" $ctx | nindent 4 }}
  annotations:
    {{- $gw.annotations | toYaml | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gateways.serviceAccountName" $ctx }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gateways.labels" $ctx | nindent 4 }}
  annotations:
    {{- $gw.annotations | toYaml | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gateways.serviceAccountName" $ctx }}
subjects:
- kind: ServiceAccount
  name: {{ include "gateways.serviceAccountName" $ctx }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
