{{- if .Values.gateways }}
{{- range .Values.gateways }}
{{- if .enabled }}
{{- $gw := mustMergeOverwrite (deepCopy $.Values.gatewayDefaults) . }}
{{- $ctx := dict "gw" $gw "Chart" $.Chart "Release" $.Release }}
{{- if $gw.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateways.serviceAccountName" $ctx }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gateways.labels" $ctx | nindent 4 }}
  {{- with $gw.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
