{{- if not .Values.prismCredentialsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-prism-credentials" .Release.Name }}
  namespace: {{ (include "k8s-agent.namespace" .) | quote }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
type: kubernetes.io/basic-auth
data:
  username: {{ required "pc.username is required when prismCredentialsSecretName is not set" .Values.pc.username | b64enc}}
  password: {{ required "pc.password is required when prismCredentialsSecretName is not set" .Values.pc.password | b64enc}}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-agent-postdelete
  namespace: {{ (include "k8s-agent.namespace" .) | quote }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-agent-postdelete
  namespace: {{ (include "k8s-agent.namespace" .) | quote }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - pods
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - list
      - patch
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - daemonsets
      - replicasets
    verbs:
      - get
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - get
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs:
      - list
  - apiGroups: ["config.openshift.io"]
    resources:
      - infrastructures
    verbs:
      - get
  - apiGroups: ["dataservices.nutanix.com"]
    resources:
      - applications
      - applicationsnapshots
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
  - apiGroups: [""]
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
  - apiGroups: [""]
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - selfsubjectaccessreviews
    verbs:
      - create
  - apiGroups: ["networking.nutanix.com"]
    resources:
      - addressgroups
      - applicationpolicies
      - isolationpolicies
      - ovninterconnects
      - vpcfederations
      - vpcs
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-agent-postdelete
  namespace: {{ (include "k8s-agent.namespace" .) | quote }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-agent-postdelete
subjects:
- kind: ServiceAccount
  name: k8s-agent-postdelete
  namespace: {{ (include "k8s-agent.namespace" .) | quote }}
---
apiVersion: v1
kind: Pod
metadata:
  name: hook-postdelete
  namespace: {{ (include "k8s-agent.namespace" .) | quote }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  {{- if eq .Values.agent.image.privateRegistry true}}
  imagePullSecrets:
  - name: nutanix-k8s-agent-pull-secret
  {{- end }}
  securityContext:
    runAsUser: 9999
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: k8s-agent-postdelete
  volumes:
  - name: pc-creds-volume
    secret:
      secretName: {{ .Values.prismCredentialsSecretName | default (printf "%s-prism-credentials" .Release.Name) }}
  {{- if include "k8s-agent.shouldMountTrustBundle" . }}
  - name: additional-trust-bundle-volume
    configMap:
      name: {{ include "k8s-agent.trustBundleConfigMapName" . }}
      items:
        - key: ca.crt
          path: ca.crt
  {{- end }}
  containers:
  - name: hook-postdelete-container
    image: "{{ .Values.agent.image.repository }}/{{ .Values.agent.image.name }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
    command: ["/k8s-agent/k8s-agent"]
    env:
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    volumeMounts:
      - name: pc-creds-volume
        mountPath: /certs
        readOnly: true
      {{- if include "k8s-agent.shouldMountTrustBundle" . }}
      - name: additional-trust-bundle-volume
        mountPath: /ca-certificate
        readOnly: true
      {{- end }}
    args:
      [
        "--chart-hook=post-delete",
        "--pc-endpoint={{ required "Endpoint is required" .Values.pc.endpoint }}",
        "--pc-port={{ .Values.pc.port }}",
        "--insecure={{ .Values.pc.insecure }}",
        "--k8s-cluster-name={{ required "Name of kubernetes cluster is required" .Values.k8sClusterName }}",
        "--k8s-distribution={{ required "Kubernetes distribution is required" .Values.k8sDistribution }}",
        "--k8s-cluster-category={{ .Values.categoryMappings }}",
        "--update-config-in-min={{ .Values.agent.updateConfigInMin }}",
        "--update-metrics-in-min={{ .Values.agent.updateMetricsInMin }}",
      ]
    securityContext:
      runAsUser: 9999
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL       
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
---
{{- include "k8s-agent.validateTrustBundle" . }}
{{- if include "k8s-agent.shouldCreateTrustBundleConfigMap" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-agent.trustBundleConfigMapName" . }}
  namespace: {{ include "k8s-agent.namespace" . | quote }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
data:
  ca.crt: {{ .Values.pc.additionalTrustBundle }}
{{- end }}
